#!/command/with-contenv bash

exec 2>&1

# If the project is composer-based
if [ -f "/app/composer.json" ]; then
  # Check if the script uses a "dev" script and run it.
  if jq -e '.scripts.dev | type == "array"' /app/composer.json > /dev/null; then
    cd /app
    echo "Executing composer.json 'dev' script" > /dev/stdout
    exec s6-setuidgid $USER /usr/local/sbin/composer /app/composer.json run dev
  # Check if it's a laravel project and run Artisan Serve.
  elif jq -e '.require["laravel/framework"]' /app/composer.json > /dev/null; then
    echo "Executing Laravel Server" > /dev/stdout
    exec s6-setuidgid $USER /usr/bin/php /app/artisan serve --port=80 --address=0.0.0.0
  fi
fi

# If there is a web server public file
if [ -f "/app/public/index.php" ]; then
  # Execute the project manually
  echo "Executing PHP Built-in Server on /app/public" > /dev/stdout
  exec s6-setuidgid $USER /usr/bin/php -S 0.0.0.0:80 -t /app/public /app/public/index.php
fi

# If the directory is not empty, then just run it.
if [ "$(ls -A /app)" ]; then
  echo "Executing PHP Built-in Server on /app" > /dev/stdout
  exec s6-setuidgid $USER /usr/bin/php -S 0.0.0.0:80 -t /app
fi

# Exit since there is nothing to server
echo "No project mounted in /app to run a web server" > /dev/stdout

exit 0
